import Head from "next/head";
import styles from "../styles/PageLayout.module.scss";
import Link from "next/link";

export default function PageLayout({children,title='NewsApp'}) {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Link className={styles.header} href='/'>Api Rick&Morty</Link>
      <main>{children}</main>
    </>
  );
}
